DROP TABLE IF EXISTS deal;
DROP TABLE IF EXISTS deal_log;

CREATE TABLE deal (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  target_url TEXT NOT NULL,
  css_selector TEXT NOT NULL
);

CREATE TABLE deal_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deal_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deal_text TEXT NOT NULL,
  FOREIGN KEY (deal_id) REFERENCES deal (id)
);